### Test Localhost /health API end point
GET http://localhost:8080/health

### Test Localhost /products API end point
GET http://localhost:8080/products 

### Test creating an order
POST http://localhost:8080/orders
Content-Type: application/json

{
    "customerId": 2,
    "items": [
        {
            "productId": 2,
            "quantity": 10
        },
        {
            "productId": 3,
            "quantity": 2
        }
    ]
}